project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu:
          - text: Hands-on Exercise 1 (part i)
            href: Handson_ex01/Hands-on_Ex01.html
          - text: Hands-on Exercise 1 (part ii)
            href: Handson_ex01/Hands-on_Ex01_2.html
          - text: Hands-on Exercise 2 (part i)
            href: Handson_ex02/Hands-on_Ex02.html
          - text: Hands-on Exercise 2 (part ii)
            href: Handson_ex02/Hands-on_Ex02_2.html
          - text: Hands-on Exercise 2 (part iii)
            href: Handson_ex02/Hands-on_Ex02_3.html
          - text: Hands-on Exercise 3
            href: Handson_ex03/Hands-on_Ex03.html
          - text: Hands-on Exercise 4
      - text: In-class Exercise
        menu:
          - text: In-class Exercise 1
            href: Inclass_ex1/inclass_ex1.html
          - text: In-class Exercise 2
            href: Inclass_ex2/inclass_ex2.html
          - text: In-class Exercise 3
            href: Inclass_ex3/Inclass_ex3.html
          - text: In-Class Exercise 4
      - text: Take-home Exercise
        menu:
          - text: Take Home Exercise 1
            href: Takehome_ex01/takehome_ex1.html
          - text: Take Home Exercise 2
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual


