project:
  type: website

website:
  title: "ISSS624"
  <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="#">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="search" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
  
  navbar:
    left:
      - text: Hands-on Exercises
        menu:
          - text: Hands-on Exercise 1 (part i)
            href: Handson_ex01/Hands-on_Ex01.html
          - text: Hands-on Exercise 1 (part ii)
            href: Handson_ex01/Hands-on_Ex01_2.html
          - text: Hands-on Exercise 2 (part i)
            href: Handson_ex02/Hands-on_Ex02.html
          - text: Hands-on Exercise 2 (part ii)
            href: Handson_ex02/Hands-on_Ex02_2.html
          - text: Hands-on Exercise 2 (part iii)
            href: Handson_ex02/Hands-on_Ex02_3.html
          - text: Hands-on Exercise 3
            href: Handson_ex03/Hands-on_Ex03.html
      - text: In-class Exercise
        menu:
          - text: In-class Exercise 1
            href: Inclass_ex1/inclass_ex1.html
          - text: In-class Exercise 2
            href: Inclass_ex2/inclass_ex2.html
          - text: In-class Exercise 3
            href: Inclass_ex3/inclass_ex3.html
      - text: Take-home Exercise
        menu:
          - text: Take Home Exercise 1
            href: Takehome_ex01/takehome_ex1.html
          - text: Take Home Exercise 2
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual


