project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu:
          - text: Hands-on Exercise 1 (part i)
            href: Handson_ex01/Hands-on_Ex01.html
          - text: Hands-on Exercise 1 (part ii)
            href: Handson_ex01/Hands-on_Ex01_2.html
      - text: In-class Exercise
        menu:
          - text: In-class Exercise 1
            href: Inclass_ex1/inclass_ex1.html
      - text: Take-home Exercise
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
